version: '3.8'

services:
  yolink-exporter:
    build: .
    ports:
      - "8080:8080"
    environment:
      - YOLINK_API_KEY=${YOLINK_API_KEY}
      - YOLINK_SECRET=${YOLINK_SECRET}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 